services:
    fabricekabongo.auth0.services.apikeyuserauthenticator:
        class:  FabriceKabongo\Auth0\APIAuthenticationBundle\Security\ApiKeyAuthenticator
        public: false
    fabricekabongo.auth0.services.apikeyuserprovider:
        class: FabriceKabongo\Auth0\APIAuthenticationBundle\Security\ApiKeyUserProvider
        arguments: ["%fabricekabongo.auth0.apiauthentication.valid_audiences%", "%fabricekabongo.auth0.apiauthentication.valid_audiences%"]